### ISSUE TITLE
Update with added features from react maintenance planner

### ISSUE THREAD

**Issue by LaChope** [kbss-cvut/react-calendar-timeline#1]
As agreed in https://github.com/kbss-cvut/react-maintenance-planner/issues/66, following features should be added in this repo:

- Resizable sidebar

@PluharVit Can you complete with other features here?

**Comment by PluharVit** [comment]
There are, as you mentioned, created handlers for sidebar resizability. 

Another update is the way to create react context
- from createReactContext
- to React.createContext
- (It was not working with createReactContext)

Changed the cursor style to resize tasks.

Zoom when ~~altKey~~ ctrlKey is down.  

New Timeline.css file. 

That should be all.

**Comment by LaChope** [comment]
Solved with https://github.com/kbss-cvut/react-calendar-timeline/commit/aaefdb111fdfe491513dc09a64d63a6c60699fa5
